stamps=stamps\disc.st \
	stamps\water.st \
	stamps\visu.st \
	stamps\visu_c.st \
	stamps\twist.st \
	stamps\techno.st \
	stamps\start.st \
	stamps\plzpart.st \
	stamps\panic.st \
	stamps\pam.st \
	stamps\lens.st \
	stamps\jplogo.st \
	stamps\grid.st \
	stamps\glenz.st \
	stamps\fcp.st \
	stamps\endscrl.st \
	stamps\endpic.st \
	stamps\end.st \
	stamps\dots.st \
	stamps\ddstars.st \
	stamps\credits.st \
	stamps\coman.st \
	stamps\beg.st \
	stamps\alku.st

all : $(stamps) 

stamps\disc.st:
	cd dis
	nmake disc.obj
	cd ..
	copy dis\disc.obj alku
	copy dis\disc.obj credits
	copy dis\disc.obj endscrl
	copy dis\disc.obj pam
	copy dis\disc.obj panic
	copy dis\disc.obj plzpart
	copy nul $@

stamps\alku.st:
	cd alku
	make -falku
	cd ..
	copy nul $@

stamps\beg.st:
	cd beg
	nmake
	cd ..
	copy nul $@

stamps\coman.st:
	cd coman
	nmake
	cd ..
	copy nul $@

stamps\credits.st:
	cd credits
	cd pics
	-cmd /c sfd
	cd ..
	-cmd /c unpack
	make -fcred
	cd ..
	copy nul $@

stamps\ddstars.st:
	cd ddstars
	nmake
	cd ..
	copy nul $@

stamps\dots.st:
	cd dots
	nmake
	cd ..
	copy nul $@

stamps\end.st:
	cd end
	nmake
	cd ..
	copy nul $@

stamps\endpic.st:
	cd endpic
	nmake
	cd ..
	copy nul $@

stamps\endscrl.st:
	cd endscrl
	make -fendscrl
	cd ..
	copy nul $@

stamps\fcp.st:
	cd fcp
	make -ffcp fcprot.exe
	cd ..
	copy nul $@

stamps\glenz.st:
	cd glenz
	nmake
	cd ..
	copy nul $@

stamps\grid.st:
	cd grid
	nmake
	cd ..
	copy nul $@

stamps\jplogo.st:
	cd jplogo
	nmake
	cd ..
	copy nul $@

stamps\lens.st:
	cd lens
	nmake
	cd ..
	copy nul $@

stamps\pam.st:
	cd pam
	make -fanim
	make -fpam
	cd ..
	copy nul $@

stamps\panic.st:
	cd panic
	make -fsd
	cd ..
	copy nul $@

stamps\plzpart.st:
	cd plzpart
	make -fplzpart
	cd ..
	copy nul $@

stamps\start.st:
	cd start
	nmake
	cd ..
	copy nul $@

stamps\techno.st:
	cd techno
	nmake
	cd ..
	copy nul $@

stamps\twist.st:
	cd twist
	nmake
	cd ..
	copy nul $@

stamps\visu.st:
	cd visu
	nmake
	cd ..
	copy nul $@

stamps\visu_c.st:
	cd visu\c
	nmake u2a.exe u2e.exe
	cd ..\..
	copy nul $@

stamps\water.st:
	cd water
	tasm routines
	bpc /m demo
	cd ..
	copy nul $@
