all : u2a.exe u2e.exe

# objects

# option flags

asm_f	= /ML /m9 /s /JJUMPS
cdeb_f	= /AL /c /W2 /Zi
c_f	= /AL /Oxaz /W2 /c

# general compile orders

.asm.obj : 
	tasm $(asm_f) $<
	
.c.obj : 
	cl /qc $(c_f) $<

u2a.exe : u2a.obj _bg.obk ..\visu.lib
	link /E /ST:2048 u2a.obj+_bg.obk+..\..\dis\disc.obj,u2a.exe,nul,..\visu.lib;
	copy u2a.exe ..\..\main\data

u2e.exe : u2e.obj ..\visu.lib
	link /E /ST:2048 u2e.obj ..\..\dis\disc.obj,u2e.exe,nul,..\visu.lib;
	copy u2e.exe ..\..\main\data

_bg.obk: u2abg.uh
	..\..\util\doobj u2abg.uh _bg $@

u2abg.uh: u2abg.lbm
	-..\..\util\lbm2u u2abg.lbm $@
