all : beg.exe 

# objects

objs=beg.obj asm.obj _pic.obk

# option flags

asm_f	= /ML /m9 /s /JJUMPS
c_f	= /AL /c /W3

# general compile orders

.asm.obj : 
	tasm $(asm_f) $<
	
.c.obj : 
	cl /qc $(c_f) $<

beg.exe : $(objs)
	link /E $(objs)+..\dis\disc.obj,beg.exe,nul;
	copy beg.exe ..\main\data\beglogo.exe
	
_pic.obk: srtitle.up
	..\util\doobj srtitle.up _pic $@

srtitle.up: srtitle.lbm
	-..\util\lbm2p srtitle.lbm $@
