all : doobj.exe getslice.exe incbin.exe lbm2p.exe lbm2u.exe

# objects

#objs=jp.obj asm.obj

# option flags

asm_f	= /ML /m9 /s /JJUMPS
c_f	= /AL /c /W3 /Oxaz

# general compile orders

.asm.obj :
	tasm $(asm_f) $<

.c.obj :
	cl $(c_f) $<

doobj.exe : doobj.obj
	link /E doobj.obj,$@,nul;

getslice.exe : getslice.obj
	link /E getslice.obj,$@,nul;

incbin.exe : incbin.obj
	link /E incbin.obj,$@,nul;

lbm2p.exe : lbm2p.obj
	link /E lbm2p.obj,$@,nul;

lbm2u.exe : lbm2u.obj
	link /E lbm2u.obj,$@,nul;
