all: demo.exe

binobjs=bkg.obj wat1.obj wat2.obj wat3.obj wat4.obj

.asm.obj:
	tasm $<

demo.exe: demo.pas t1.pas t2.pas t3.pas bkr.pas miek.pas routines.obj miekka.obj $(binobjs)
	bpc /m demo

bkg.obj: bkg.asm bkg.inc

wat1.obj: wat1.asm wat1.inc

wat2.obj: wat2.asm wat2.inc

wat3.obj: wat3.asm wat3.inc

wat4.obj: wat4.asm wat4.inc

bkg.uh: bkg.lbm
	-..\util\lbm2u bkg.lbm $@

bkg.inc: bkg.uh
	..\util\incbin bkg.uh $@

wat1.inc: wat1.dat
	..\util\incbin wat1.dat $@

wat2.inc: wat2.dat
	..\util\incbin wat2.dat $@

wat3.inc: wat3.dat
	..\util\incbin wat3.dat $@

wat4.inc: wat4.dat
	..\util\incbin wat4.dat $@

miekka.uh: miekka.lbm
	-..\util\lbm2u miekka.lbm $@

miekka.obj: miekka.uh
	binobj miekka.uh miekka.obj _miekka
