all : lens.exe calc.exe

#after lensexb, there must be 4K of data (filler) for 64K overflow
data1=_lensexb.obk _filler.obk _lensex1.obk _lensex0.obk 
data2=_lensex2.obk _lensex3.obk _lensex4.obk
code1=main.obj asm.obj ..\dis\disc.obj
objs=$(code1) $(data1) $(data2)

asm_f	= /ML /m2 /s /JJUMPS
#c_f	= /AL /c /W1 /qc
c_f	= /AL /c /W1 /Oxaz

.asm.obj :
	tasm $(asm_f) $<
	
.c.obj :
	cl $(c_f) $<

lens.exe : $(objs)
	echo /E + > link.tmp 
	echo $(code1) + >> link.tmp
	echo $(data1) + >> link.tmp
	echo $(data2) >> link.tmp
	echo ,lens.exe,lens.map; >> link.tmp
	link @link.tmp
	copy lens.exe ..\main\data\lnszoom.exe

calc.exe : calc.c
	cl /W3 /AL calc.c

_filler.obk:
	..\util\doobj filler _filler $@

_lensex0.obk: lens.ex0
	..\util\doobj lens.ex0 _lensex0 $@

_lensex1.obk: lens.ex1
	..\util\doobj lens.ex1 _lensex1 $@

_lensex2.obk: lens.ex2
	..\util\doobj lens.ex2 _lensex2 $@

_lensex3.obk: lens.ex3
	..\util\doobj lens.ex3 _lensex3 $@

_lensex4.obk: lens.ex4
	..\util\doobj lens.ex4 _lensex4 $@

_lensexb.obk: lens.exb
	..\util\doobj lens.exb _lensexb $@

lens.exb: lenspic.lbm
	-..\util\lbm2u lenspic.lbm $@

lens.uh: lens.lbm
	-..\util\lbm2u lens.lbm $@

lens.ex1 lens.ex0 lens.ex2 lens.ex3 lens.ex4: calc.exe lens.uh
	calc
